project_id: '881634'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: /lib/l10n/app_en_US.arb
    translation: /lib/l10n/app_%locale_with_underscore%.arb
    languages_mapping:
      locale_with_underscore:
        de: de_DE
        qm: de_QM
