// Generated by tool/generate_notification_push_l10n.dart from lib/l10n/app_*.arb.
// Regenerate from the repository root with:
// dart run tool/generate_notification_push_l10n.dart

export type NotificationPushInput = {
  type: string;
  locale: string;
  templateArgs: Record<string, unknown> | null;
  senderDisplayName: string;
};

type NotificationMessage = {
  title: string;
  body?: string;
};

const fallbackLocale = "en";
const fallbackTitle = "Glass Trail";

const messages: Record<string, Record<string, NotificationMessage>> = {
  "de": {
    "friend_request_sent": {
      "title": "{name} hat dir eine Freundschaftsanfrage gesendet",
      "body": "Prüfe sie in deinem Freunde-Bereich.",
    },
    "friend_request_accepted": {
      "title": "{name} hat deine Freundschaftsanfrage angenommen",
      "body": "Ihr könnt jetzt gegenseitig geteilte Aktivitäten sehen.",
    },
    "friend_request_rejected": {
      "title": "{name} hat deine Freundschaftsanfrage abgelehnt",
      "body": "Du kannst später eine neue Anfrage senden.",
    },
    "friend_removed": {
      "title": "{name} hat dich als Freund entfernt",
      "body": "Öffne deinen Freunde-Bereich, um deine Verbindungen zu prüfen.",
    },
    "friend_drink_logged": {
      "title": "{name} trinkt {drink}",
      "body": "{commentLine}\n{locationAddressLine}",
    },
  },
  "en": {
    "friend_request_sent": {
      "title": "{name} sent you a friend request",
      "body": "Review it in your Friends section.",
    },
    "friend_request_accepted": {
      "title": "{name} accepted your friend request",
      "body": "You can now see each other's shared activity.",
    },
    "friend_request_rejected": {
      "title": "{name} declined your friend request",
      "body": "You can send another request later.",
    },
    "friend_removed": {
      "title": "{name} removed you as a friend",
      "body": "Open your Friends section to review your connections.",
    },
    "friend_drink_logged": {
      "title": "{name} drinks {drink}",
      "body": "{commentLine}\n{locationAddressLine}",
    },
  },
};
const defaultDrinkNames: Record<string, Record<string, string>> = {
  "en": {
    "appleWines-apple-wine": "Apple Wine",
    "appleWines-cider": "Cider",
    "appleWines-hard-seltzer": "Hard Seltzer",
    "beer-alt": "Alt",
    "beer-can": "Beer Can",
    "beer-classic": "Beer",
    "beer-goassmass": "Goaßmaß",
    "beer-helles": "Helles",
    "beer-ipa": "IPA",
    "beer-kellerbier": "Kellerbier",
    "beer-kölsch": "Kölsch",
    "beer-mass": "Maß",
    "beer-non-alcoholic": "Non-alcoholic Beer",
    "beer-pils": "Pils",
    "beer-radler": "Radler",
    "beer-stout": "Stout",
    "beer-weizen": "Weizen",
    "cocktails-caipirinha": "Caipirinha",
    "cocktails-cocktail": "Cocktail",
    "cocktails-margarita": "Margarita",
    "cocktails-martini": "Martini",
    "cocktails-mojito": "Mojito",
    "longdrinks-cuba-libre": "Cuba Libre",
    "longdrinks-gin-tonic": "Gin & Tonic",
    "longdrinks-jacki-cola": "Jacki Cola",
    "longdrinks-longdrink": "Longdrink",
    "longdrinks-vodka-bull": "Vodka Bull",
    "longdrinks-vodka-o": "Vodka O",
    "nonAlcoholic-club-mate": "Club-Mate",
    "nonAlcoholic-coffee": "Coffee",
    "nonAlcoholic-cola": "Cola",
    "nonAlcoholic-energy-drink": "Energy Drink",
    "nonAlcoholic-juice": "Juice",
    "nonAlcoholic-lemonade": "Lemonade",
    "nonAlcoholic-mate-tea": "Mate Tea",
    "nonAlcoholic-sparkling-water": "Sparkling Water",
    "nonAlcoholic-tea": "Tea",
    "nonAlcoholic-water": "Water",
    "shots-berliner-luft": "Berliner Luft",
    "shots-ficken": "Ficken",
    "shots-jaegermeister": "Jägermeister",
    "shots-limoncello": "Limoncello",
    "shots-pfeffi": "Pfeffi",
    "shots-shot": "Shot",
    "sparklingWines-champagne": "Champagne",
    "spirits-cognac": "Cognac",
    "spirits-gin": "Gin",
    "spirits-rum": "Rum",
    "spirits-tequila": "Tequila",
    "spirits-vodka": "Vodka",
    "spirits-whiskey": "Whiskey",
    "wine-aperol-spritz": "Aperol Spritz",
    "wine-mulled-wine": "Mulled Wine",
    "wine-red-wine": "Red Wine",
    "wine-rosé-wine": "Rosé Wine",
    "wine-sangria": "Sangria",
    "wine-sparkling-wine": "Sparkling Wine",
    "wine-spritzer": "Spritzer",
    "wine-white-wine": "White Wine",
    "wine-wine-spritzer": "Wine Spritzer",
  },
  "de": {
    "appleWines-apple-wine": "Apfelwein",
    "appleWines-cider": "Cider",
    "appleWines-hard-seltzer": "Hard Seltzer",
    "beer-alt": "Alt",
    "beer-can": "Dosenbier",
    "beer-classic": "Bier",
    "beer-goassmass": "Goaßmaß",
    "beer-helles": "Helles",
    "beer-ipa": "IPA",
    "beer-kellerbier": "Kellerbier",
    "beer-kölsch": "Kölsch",
    "beer-mass": "Maß",
    "beer-non-alcoholic": "Alkoholfreies Bier",
    "beer-pils": "Pils",
    "beer-radler": "Radler",
    "beer-stout": "Stout",
    "beer-weizen": "Weizen",
    "cocktails-caipirinha": "Caipirinha",
    "cocktails-cocktail": "Cocktail",
    "cocktails-margarita": "Margarita",
    "cocktails-martini": "Martini",
    "cocktails-mojito": "Mojito",
    "longdrinks-cuba-libre": "Cuba Libre",
    "longdrinks-gin-tonic": "Gin & Tonic",
    "longdrinks-jacki-cola": "Jacki Cola",
    "longdrinks-longdrink": "Longdrink",
    "longdrinks-vodka-bull": "Vodka Bull",
    "longdrinks-vodka-o": "Vodka O",
    "nonAlcoholic-club-mate": "Club-Mate",
    "nonAlcoholic-coffee": "Kaffee",
    "nonAlcoholic-cola": "Cola",
    "nonAlcoholic-energy-drink": "Energy Drink",
    "nonAlcoholic-juice": "Saft",
    "nonAlcoholic-lemonade": "Limonade",
    "nonAlcoholic-mate-tea": "Mate Tee",
    "nonAlcoholic-sparkling-water": "Sprudelwasser",
    "nonAlcoholic-tea": "Tee",
    "nonAlcoholic-water": "Wasser",
    "shots-berliner-luft": "Berliner Luft",
    "shots-ficken": "Ficken",
    "shots-jaegermeister": "Jägermeister",
    "shots-limoncello": "Limoncello",
    "shots-pfeffi": "Pfeffi",
    "shots-shot": "Shot",
    "sparklingWines-champagne": "Champagner",
    "spirits-cognac": "Cognac",
    "spirits-gin": "Gin",
    "spirits-rum": "Rum",
    "spirits-tequila": "Tequila",
    "spirits-vodka": "Wodka",
    "spirits-whiskey": "Whiskey",
    "wine-aperol-spritz": "Aperol Spritz",
    "wine-mulled-wine": "Glühwein",
    "wine-red-wine": "Rotwein",
    "wine-rosé-wine": "Roséwein",
    "wine-sangria": "Sangria",
    "wine-sparkling-wine": "Sekt",
    "wine-spritzer": "Spritzer",
    "wine-white-wine": "Weißwein",
    "wine-wine-spritzer": "Weinschorle",
  },
};

export function notificationPushTitle(input: NotificationPushInput): string {
  const title = messageFor(input.type, input.locale)?.title ?? fallbackTitle;
  return formatTemplate(title, input);
}

export function notificationPushBody(
  input: NotificationPushInput,
): string | null {
  const body = messageFor(input.type, input.locale)?.body;
  return body == null ? null : compactBody(formatTemplate(body, input));
}

function messageFor(type: string, locale: string): NotificationMessage | null {
  const normalizedLocale = normalizeLocale(locale);
  return messages[normalizedLocale]?.[type] ??
    messages[languageFromLocale(normalizedLocale)]?.[type] ??
    messages[fallbackLocale]?.[type] ??
    null;
}

function formatTemplate(
  template: string,
  input: NotificationPushInput,
): string {
  return template
    .replaceAll("{name}", senderDisplayName(input))
    .replaceAll("{drink}", localizedDrinkName(input))
    .replaceAll(
      "{commentLine}",
      prefixedNotificationLine("🗨️", templateString(input, "comment")),
    )
    .replaceAll(
      "{locationAddressLine}",
      prefixedNotificationLine(
        "📍",
        templateString(input, "locationAddress", "location_address"),
      ),
    )
    .replaceAll("{comment}", templateString(input, "comment"))
    .replaceAll(
      "{locationAddress}",
      templateString(input, "locationAddress", "location_address"),
    );
}

function senderDisplayName(input: NotificationPushInput): string {
  const fromTemplateArgs = templateString(
    input,
    "senderDisplayName",
    "sender_display_name",
  );
  if (fromTemplateArgs.length > 0) {
    return fromTemplateArgs;
  }

  const fromRow = stringValue(input.senderDisplayName);
  return fromRow.length > 0 ? fromRow : "Glass Trail User";
}

function localizedDrinkName(input: NotificationPushInput): string {
  const drinkId = templateString(input, "drinkId", "drink_id");
  const locale = languageFromLocale(normalizeLocale(input.locale));
  const localized = stringValue(defaultDrinkNames[locale]?.[drinkId]) ||
    stringValue(defaultDrinkNames[fallbackLocale]?.[drinkId]);
  if (localized.length > 0) {
    return localized;
  }
  return templateString(input, "drinkName", "drink_name") || "a drink";
}

function templateString(
  input: NotificationPushInput,
  primary: string,
  fallback?: string,
): string {
  return stringValue(input.templateArgs?.[primary]) ||
    (fallback == null ? "" : stringValue(input.templateArgs?.[fallback]));
}

function prefixedNotificationLine(prefix: string, value: string): string {
  return value.length > 0 ? `${prefix} ${value}` : "";
}

function compactBody(value: string): string | null {
  const body = value
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join("\n");
  return body.length > 0 ? body : null;
}

function normalizeLocale(value: string): string {
  const locale = stringValue(value).replaceAll("_", "-");
  return locale.length > 0 ? locale : fallbackLocale;
}

function languageFromLocale(locale: string): string {
  return locale.split("-")[0] || fallbackLocale;
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}
