// Generated by tool/generate_notification_push_l10n.dart from lib/l10n/app_*.arb.
// Regenerate from the repository root with:
// dart run tool/generate_notification_push_l10n.dart

export type NotificationPushInput = {
  type: string;
  locale: string;
  templateArgs: Record<string, unknown> | null;
  senderDisplayName: string;
};

type NotificationMessage = {
  title: string;
  body?: string;
};

const fallbackLocale = "en";
const fallbackTitle = "Glass Trail";

const messages: Record<string, Record<string, NotificationMessage>> = {
  "de": {
    "friend_request_sent": {
      "title": "{name} hat dir eine Freundschaftsanfrage gesendet",
      "body": "Prüfe sie in deinem Freunde-Bereich.",
    },
    "friend_request_accepted": {
      "title": "{name} hat deine Freundschaftsanfrage angenommen",
      "body": "Ihr könnt jetzt gegenseitig geteilte Aktivitäten sehen.",
    },
    "friend_request_rejected": {
      "title": "{name} hat deine Freundschaftsanfrage abgelehnt",
      "body": "Du kannst später eine neue Anfrage senden.",
    },
    "friend_removed": {
      "title": "{name} hat dich als Freund entfernt",
      "body": "Öffne deinen Freunde-Bereich, um deine Verbindungen zu prüfen.",
    },
  },
  "en": {
    "friend_request_sent": {
      "title": "{name} sent you a friend request",
      "body": "Review it in your Friends section.",
    },
    "friend_request_accepted": {
      "title": "{name} accepted your friend request",
      "body": "You can now see each other's shared activity.",
    },
    "friend_request_rejected": {
      "title": "{name} declined your friend request",
      "body": "You can send another request later.",
    },
    "friend_removed": {
      "title": "{name} removed you as a friend",
      "body": "Open your Friends section to review your connections.",
    },
  },
};

export function notificationPushTitle(input: NotificationPushInput): string {
  const title = messageFor(input.type, input.locale)?.title ?? fallbackTitle;
  return formatTemplate(title, input);
}

export function notificationPushBody(
  input: NotificationPushInput,
): string | null {
  const body = messageFor(input.type, input.locale)?.body;
  return body == null ? null : formatTemplate(body, input);
}

function messageFor(type: string, locale: string): NotificationMessage | null {
  const normalizedLocale = normalizeLocale(locale);
  return messages[normalizedLocale]?.[type] ??
    messages[languageFromLocale(normalizedLocale)]?.[type] ??
    messages[fallbackLocale]?.[type] ??
    null;
}

function formatTemplate(
  template: string,
  input: NotificationPushInput,
): string {
  return template.replaceAll("{name}", senderDisplayName(input));
}

function senderDisplayName(input: NotificationPushInput): string {
  const fromTemplateArgs =
    stringValue(input.templateArgs?.["senderDisplayName"]) ||
    stringValue(input.templateArgs?.["sender_display_name"]);
  if (fromTemplateArgs.length > 0) {
    return fromTemplateArgs;
  }

  const fromRow = stringValue(input.senderDisplayName);
  return fromRow.length > 0 ? fromRow : "Glass Trail User";
}

function normalizeLocale(value: string): string {
  const locale = stringValue(value).replaceAll("_", "-");
  return locale.length > 0 ? locale : fallbackLocale;
}

function languageFromLocale(locale: string): string {
  return locale.split("-")[0] || fallbackLocale;
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}
