/// Resolves an achievement catalog string key (titleKey / descriptionKey /
/// familyTitleKey / countryLabelKey) to its localized text.
///
/// Mechanically generated from docs/achievements/strings.md and
/// arb-key-plan.md -- keep in sync with lib/l10n/app_en.arb and
/// lib/l10n/app_de.arb rather than hand-editing the switch below.
library;

import 'package:glasstrail/l10n/app_localizations.dart';

String resolveAchievementString(AppLocalizations l10n, String key) {
  switch (key) {
    case 'achievementFamilyTotalDrinksTitle':
      return l10n.achievementFamilyTotalDrinksTitle;
    case 'achievementFamilyTotalDrinksLevel1Title':
      return l10n.achievementFamilyTotalDrinksLevel1Title;
    case 'achievementFamilyTotalDrinksLevel1Description':
      return l10n.achievementFamilyTotalDrinksLevel1Description;
    case 'achievementFamilyTotalDrinksLevel10Title':
      return l10n.achievementFamilyTotalDrinksLevel10Title;
    case 'achievementFamilyTotalDrinksLevel10Description':
      return l10n.achievementFamilyTotalDrinksLevel10Description;
    case 'achievementFamilyTotalDrinksLevel25Title':
      return l10n.achievementFamilyTotalDrinksLevel25Title;
    case 'achievementFamilyTotalDrinksLevel25Description':
      return l10n.achievementFamilyTotalDrinksLevel25Description;
    case 'achievementFamilyTotalDrinksLevel50Title':
      return l10n.achievementFamilyTotalDrinksLevel50Title;
    case 'achievementFamilyTotalDrinksLevel50Description':
      return l10n.achievementFamilyTotalDrinksLevel50Description;
    case 'achievementFamilyTotalDrinksLevel100Title':
      return l10n.achievementFamilyTotalDrinksLevel100Title;
    case 'achievementFamilyTotalDrinksLevel100Description':
      return l10n.achievementFamilyTotalDrinksLevel100Description;
    case 'achievementFamilyTotalDrinksLevel200Title':
      return l10n.achievementFamilyTotalDrinksLevel200Title;
    case 'achievementFamilyTotalDrinksLevel200Description':
      return l10n.achievementFamilyTotalDrinksLevel200Description;
    case 'achievementFamilyTotalDrinksLevel300Title':
      return l10n.achievementFamilyTotalDrinksLevel300Title;
    case 'achievementFamilyTotalDrinksLevel300Description':
      return l10n.achievementFamilyTotalDrinksLevel300Description;
    case 'achievementFamilyTotalDrinksLevel400Title':
      return l10n.achievementFamilyTotalDrinksLevel400Title;
    case 'achievementFamilyTotalDrinksLevel400Description':
      return l10n.achievementFamilyTotalDrinksLevel400Description;
    case 'achievementFamilyTotalDrinksLevel500Title':
      return l10n.achievementFamilyTotalDrinksLevel500Title;
    case 'achievementFamilyTotalDrinksLevel500Description':
      return l10n.achievementFamilyTotalDrinksLevel500Description;
    case 'achievementFamilyTotalDrinksLevel1000Title':
      return l10n.achievementFamilyTotalDrinksLevel1000Title;
    case 'achievementFamilyTotalDrinksLevel1000Description':
      return l10n.achievementFamilyTotalDrinksLevel1000Description;
    case 'achievementFamilyStreaksTitle':
      return l10n.achievementFamilyStreaksTitle;
    case 'achievementFamilyStreaksLevel3Title':
      return l10n.achievementFamilyStreaksLevel3Title;
    case 'achievementFamilyStreaksLevel3Description':
      return l10n.achievementFamilyStreaksLevel3Description;
    case 'achievementFamilyStreaksLevel7Title':
      return l10n.achievementFamilyStreaksLevel7Title;
    case 'achievementFamilyStreaksLevel7Description':
      return l10n.achievementFamilyStreaksLevel7Description;
    case 'achievementFamilyStreaksLevel14Title':
      return l10n.achievementFamilyStreaksLevel14Title;
    case 'achievementFamilyStreaksLevel14Description':
      return l10n.achievementFamilyStreaksLevel14Description;
    case 'achievementFamilyStreaksLevel30Title':
      return l10n.achievementFamilyStreaksLevel30Title;
    case 'achievementFamilyStreaksLevel30Description':
      return l10n.achievementFamilyStreaksLevel30Description;
    case 'achievementFamilyStreaksLevel60Title':
      return l10n.achievementFamilyStreaksLevel60Title;
    case 'achievementFamilyStreaksLevel60Description':
      return l10n.achievementFamilyStreaksLevel60Description;
    case 'achievementFamilyStreaksLevel90Title':
      return l10n.achievementFamilyStreaksLevel90Title;
    case 'achievementFamilyStreaksLevel90Description':
      return l10n.achievementFamilyStreaksLevel90Description;
    case 'achievementFamilyStreaksLevel180Title':
      return l10n.achievementFamilyStreaksLevel180Title;
    case 'achievementFamilyStreaksLevel180Description':
      return l10n.achievementFamilyStreaksLevel180Description;
    case 'achievementFamilyStreaksLevel365Title':
      return l10n.achievementFamilyStreaksLevel365Title;
    case 'achievementFamilyStreaksLevel365Description':
      return l10n.achievementFamilyStreaksLevel365Description;
    case 'achievementFamilyBeerTitle':
      return l10n.achievementFamilyBeerTitle;
    case 'achievementFamilyBeerLevel10Title':
      return l10n.achievementFamilyBeerLevel10Title;
    case 'achievementFamilyBeerLevel10Description':
      return l10n.achievementFamilyBeerLevel10Description;
    case 'achievementFamilyBeerLevel25Title':
      return l10n.achievementFamilyBeerLevel25Title;
    case 'achievementFamilyBeerLevel25Description':
      return l10n.achievementFamilyBeerLevel25Description;
    case 'achievementFamilyBeerLevel50Title':
      return l10n.achievementFamilyBeerLevel50Title;
    case 'achievementFamilyBeerLevel50Description':
      return l10n.achievementFamilyBeerLevel50Description;
    case 'achievementFamilyBeerLevel100Title':
      return l10n.achievementFamilyBeerLevel100Title;
    case 'achievementFamilyBeerLevel100Description':
      return l10n.achievementFamilyBeerLevel100Description;
    case 'achievementFamilyBeerLevel200Title':
      return l10n.achievementFamilyBeerLevel200Title;
    case 'achievementFamilyBeerLevel200Description':
      return l10n.achievementFamilyBeerLevel200Description;
    case 'achievementFamilyBeerLevel300Title':
      return l10n.achievementFamilyBeerLevel300Title;
    case 'achievementFamilyBeerLevel300Description':
      return l10n.achievementFamilyBeerLevel300Description;
    case 'achievementFamilyBeerLevel400Title':
      return l10n.achievementFamilyBeerLevel400Title;
    case 'achievementFamilyBeerLevel400Description':
      return l10n.achievementFamilyBeerLevel400Description;
    case 'achievementFamilyBeerLevel500Title':
      return l10n.achievementFamilyBeerLevel500Title;
    case 'achievementFamilyBeerLevel500Description':
      return l10n.achievementFamilyBeerLevel500Description;
    case 'achievementFamilyBeerLevel1000Title':
      return l10n.achievementFamilyBeerLevel1000Title;
    case 'achievementFamilyBeerLevel1000Description':
      return l10n.achievementFamilyBeerLevel1000Description;
    case 'achievementFamilyWineTitle':
      return l10n.achievementFamilyWineTitle;
    case 'achievementFamilyWineLevel10Title':
      return l10n.achievementFamilyWineLevel10Title;
    case 'achievementFamilyWineLevel10Description':
      return l10n.achievementFamilyWineLevel10Description;
    case 'achievementFamilyWineLevel25Title':
      return l10n.achievementFamilyWineLevel25Title;
    case 'achievementFamilyWineLevel25Description':
      return l10n.achievementFamilyWineLevel25Description;
    case 'achievementFamilyWineLevel50Title':
      return l10n.achievementFamilyWineLevel50Title;
    case 'achievementFamilyWineLevel50Description':
      return l10n.achievementFamilyWineLevel50Description;
    case 'achievementFamilyWineLevel100Title':
      return l10n.achievementFamilyWineLevel100Title;
    case 'achievementFamilyWineLevel100Description':
      return l10n.achievementFamilyWineLevel100Description;
    case 'achievementFamilyWineLevel200Title':
      return l10n.achievementFamilyWineLevel200Title;
    case 'achievementFamilyWineLevel200Description':
      return l10n.achievementFamilyWineLevel200Description;
    case 'achievementFamilyWineLevel300Title':
      return l10n.achievementFamilyWineLevel300Title;
    case 'achievementFamilyWineLevel300Description':
      return l10n.achievementFamilyWineLevel300Description;
    case 'achievementFamilyWineLevel400Title':
      return l10n.achievementFamilyWineLevel400Title;
    case 'achievementFamilyWineLevel400Description':
      return l10n.achievementFamilyWineLevel400Description;
    case 'achievementFamilyWineLevel500Title':
      return l10n.achievementFamilyWineLevel500Title;
    case 'achievementFamilyWineLevel500Description':
      return l10n.achievementFamilyWineLevel500Description;
    case 'achievementFamilyWineLevel1000Title':
      return l10n.achievementFamilyWineLevel1000Title;
    case 'achievementFamilyWineLevel1000Description':
      return l10n.achievementFamilyWineLevel1000Description;
    case 'achievementFamilySparklingWinesTitle':
      return l10n.achievementFamilySparklingWinesTitle;
    case 'achievementFamilySparklingWinesLevel10Title':
      return l10n.achievementFamilySparklingWinesLevel10Title;
    case 'achievementFamilySparklingWinesLevel10Description':
      return l10n.achievementFamilySparklingWinesLevel10Description;
    case 'achievementFamilySparklingWinesLevel25Title':
      return l10n.achievementFamilySparklingWinesLevel25Title;
    case 'achievementFamilySparklingWinesLevel25Description':
      return l10n.achievementFamilySparklingWinesLevel25Description;
    case 'achievementFamilySparklingWinesLevel50Title':
      return l10n.achievementFamilySparklingWinesLevel50Title;
    case 'achievementFamilySparklingWinesLevel50Description':
      return l10n.achievementFamilySparklingWinesLevel50Description;
    case 'achievementFamilySparklingWinesLevel100Title':
      return l10n.achievementFamilySparklingWinesLevel100Title;
    case 'achievementFamilySparklingWinesLevel100Description':
      return l10n.achievementFamilySparklingWinesLevel100Description;
    case 'achievementFamilySparklingWinesLevel200Title':
      return l10n.achievementFamilySparklingWinesLevel200Title;
    case 'achievementFamilySparklingWinesLevel200Description':
      return l10n.achievementFamilySparklingWinesLevel200Description;
    case 'achievementFamilySparklingWinesLevel300Title':
      return l10n.achievementFamilySparklingWinesLevel300Title;
    case 'achievementFamilySparklingWinesLevel300Description':
      return l10n.achievementFamilySparklingWinesLevel300Description;
    case 'achievementFamilySparklingWinesLevel400Title':
      return l10n.achievementFamilySparklingWinesLevel400Title;
    case 'achievementFamilySparklingWinesLevel400Description':
      return l10n.achievementFamilySparklingWinesLevel400Description;
    case 'achievementFamilySparklingWinesLevel500Title':
      return l10n.achievementFamilySparklingWinesLevel500Title;
    case 'achievementFamilySparklingWinesLevel500Description':
      return l10n.achievementFamilySparklingWinesLevel500Description;
    case 'achievementFamilySparklingWinesLevel1000Title':
      return l10n.achievementFamilySparklingWinesLevel1000Title;
    case 'achievementFamilySparklingWinesLevel1000Description':
      return l10n.achievementFamilySparklingWinesLevel1000Description;
    case 'achievementFamilyLongdrinksTitle':
      return l10n.achievementFamilyLongdrinksTitle;
    case 'achievementFamilyLongdrinksLevel10Title':
      return l10n.achievementFamilyLongdrinksLevel10Title;
    case 'achievementFamilyLongdrinksLevel10Description':
      return l10n.achievementFamilyLongdrinksLevel10Description;
    case 'achievementFamilyLongdrinksLevel25Title':
      return l10n.achievementFamilyLongdrinksLevel25Title;
    case 'achievementFamilyLongdrinksLevel25Description':
      return l10n.achievementFamilyLongdrinksLevel25Description;
    case 'achievementFamilyLongdrinksLevel50Title':
      return l10n.achievementFamilyLongdrinksLevel50Title;
    case 'achievementFamilyLongdrinksLevel50Description':
      return l10n.achievementFamilyLongdrinksLevel50Description;
    case 'achievementFamilyLongdrinksLevel100Title':
      return l10n.achievementFamilyLongdrinksLevel100Title;
    case 'achievementFamilyLongdrinksLevel100Description':
      return l10n.achievementFamilyLongdrinksLevel100Description;
    case 'achievementFamilyLongdrinksLevel200Title':
      return l10n.achievementFamilyLongdrinksLevel200Title;
    case 'achievementFamilyLongdrinksLevel200Description':
      return l10n.achievementFamilyLongdrinksLevel200Description;
    case 'achievementFamilyLongdrinksLevel300Title':
      return l10n.achievementFamilyLongdrinksLevel300Title;
    case 'achievementFamilyLongdrinksLevel300Description':
      return l10n.achievementFamilyLongdrinksLevel300Description;
    case 'achievementFamilyLongdrinksLevel400Title':
      return l10n.achievementFamilyLongdrinksLevel400Title;
    case 'achievementFamilyLongdrinksLevel400Description':
      return l10n.achievementFamilyLongdrinksLevel400Description;
    case 'achievementFamilyLongdrinksLevel500Title':
      return l10n.achievementFamilyLongdrinksLevel500Title;
    case 'achievementFamilyLongdrinksLevel500Description':
      return l10n.achievementFamilyLongdrinksLevel500Description;
    case 'achievementFamilyLongdrinksLevel1000Title':
      return l10n.achievementFamilyLongdrinksLevel1000Title;
    case 'achievementFamilyLongdrinksLevel1000Description':
      return l10n.achievementFamilyLongdrinksLevel1000Description;
    case 'achievementFamilySpiritsTitle':
      return l10n.achievementFamilySpiritsTitle;
    case 'achievementFamilySpiritsLevel10Title':
      return l10n.achievementFamilySpiritsLevel10Title;
    case 'achievementFamilySpiritsLevel10Description':
      return l10n.achievementFamilySpiritsLevel10Description;
    case 'achievementFamilySpiritsLevel25Title':
      return l10n.achievementFamilySpiritsLevel25Title;
    case 'achievementFamilySpiritsLevel25Description':
      return l10n.achievementFamilySpiritsLevel25Description;
    case 'achievementFamilySpiritsLevel50Title':
      return l10n.achievementFamilySpiritsLevel50Title;
    case 'achievementFamilySpiritsLevel50Description':
      return l10n.achievementFamilySpiritsLevel50Description;
    case 'achievementFamilySpiritsLevel100Title':
      return l10n.achievementFamilySpiritsLevel100Title;
    case 'achievementFamilySpiritsLevel100Description':
      return l10n.achievementFamilySpiritsLevel100Description;
    case 'achievementFamilySpiritsLevel200Title':
      return l10n.achievementFamilySpiritsLevel200Title;
    case 'achievementFamilySpiritsLevel200Description':
      return l10n.achievementFamilySpiritsLevel200Description;
    case 'achievementFamilySpiritsLevel300Title':
      return l10n.achievementFamilySpiritsLevel300Title;
    case 'achievementFamilySpiritsLevel300Description':
      return l10n.achievementFamilySpiritsLevel300Description;
    case 'achievementFamilySpiritsLevel400Title':
      return l10n.achievementFamilySpiritsLevel400Title;
    case 'achievementFamilySpiritsLevel400Description':
      return l10n.achievementFamilySpiritsLevel400Description;
    case 'achievementFamilySpiritsLevel500Title':
      return l10n.achievementFamilySpiritsLevel500Title;
    case 'achievementFamilySpiritsLevel500Description':
      return l10n.achievementFamilySpiritsLevel500Description;
    case 'achievementFamilySpiritsLevel1000Title':
      return l10n.achievementFamilySpiritsLevel1000Title;
    case 'achievementFamilySpiritsLevel1000Description':
      return l10n.achievementFamilySpiritsLevel1000Description;
    case 'achievementFamilyShotsTitle':
      return l10n.achievementFamilyShotsTitle;
    case 'achievementFamilyShotsLevel10Title':
      return l10n.achievementFamilyShotsLevel10Title;
    case 'achievementFamilyShotsLevel10Description':
      return l10n.achievementFamilyShotsLevel10Description;
    case 'achievementFamilyShotsLevel25Title':
      return l10n.achievementFamilyShotsLevel25Title;
    case 'achievementFamilyShotsLevel25Description':
      return l10n.achievementFamilyShotsLevel25Description;
    case 'achievementFamilyShotsLevel50Title':
      return l10n.achievementFamilyShotsLevel50Title;
    case 'achievementFamilyShotsLevel50Description':
      return l10n.achievementFamilyShotsLevel50Description;
    case 'achievementFamilyShotsLevel100Title':
      return l10n.achievementFamilyShotsLevel100Title;
    case 'achievementFamilyShotsLevel100Description':
      return l10n.achievementFamilyShotsLevel100Description;
    case 'achievementFamilyShotsLevel200Title':
      return l10n.achievementFamilyShotsLevel200Title;
    case 'achievementFamilyShotsLevel200Description':
      return l10n.achievementFamilyShotsLevel200Description;
    case 'achievementFamilyShotsLevel300Title':
      return l10n.achievementFamilyShotsLevel300Title;
    case 'achievementFamilyShotsLevel300Description':
      return l10n.achievementFamilyShotsLevel300Description;
    case 'achievementFamilyShotsLevel400Title':
      return l10n.achievementFamilyShotsLevel400Title;
    case 'achievementFamilyShotsLevel400Description':
      return l10n.achievementFamilyShotsLevel400Description;
    case 'achievementFamilyShotsLevel500Title':
      return l10n.achievementFamilyShotsLevel500Title;
    case 'achievementFamilyShotsLevel500Description':
      return l10n.achievementFamilyShotsLevel500Description;
    case 'achievementFamilyShotsLevel1000Title':
      return l10n.achievementFamilyShotsLevel1000Title;
    case 'achievementFamilyShotsLevel1000Description':
      return l10n.achievementFamilyShotsLevel1000Description;
    case 'achievementFamilyCocktailsTitle':
      return l10n.achievementFamilyCocktailsTitle;
    case 'achievementFamilyCocktailsLevel10Title':
      return l10n.achievementFamilyCocktailsLevel10Title;
    case 'achievementFamilyCocktailsLevel10Description':
      return l10n.achievementFamilyCocktailsLevel10Description;
    case 'achievementFamilyCocktailsLevel25Title':
      return l10n.achievementFamilyCocktailsLevel25Title;
    case 'achievementFamilyCocktailsLevel25Description':
      return l10n.achievementFamilyCocktailsLevel25Description;
    case 'achievementFamilyCocktailsLevel50Title':
      return l10n.achievementFamilyCocktailsLevel50Title;
    case 'achievementFamilyCocktailsLevel50Description':
      return l10n.achievementFamilyCocktailsLevel50Description;
    case 'achievementFamilyCocktailsLevel100Title':
      return l10n.achievementFamilyCocktailsLevel100Title;
    case 'achievementFamilyCocktailsLevel100Description':
      return l10n.achievementFamilyCocktailsLevel100Description;
    case 'achievementFamilyCocktailsLevel200Title':
      return l10n.achievementFamilyCocktailsLevel200Title;
    case 'achievementFamilyCocktailsLevel200Description':
      return l10n.achievementFamilyCocktailsLevel200Description;
    case 'achievementFamilyCocktailsLevel300Title':
      return l10n.achievementFamilyCocktailsLevel300Title;
    case 'achievementFamilyCocktailsLevel300Description':
      return l10n.achievementFamilyCocktailsLevel300Description;
    case 'achievementFamilyCocktailsLevel400Title':
      return l10n.achievementFamilyCocktailsLevel400Title;
    case 'achievementFamilyCocktailsLevel400Description':
      return l10n.achievementFamilyCocktailsLevel400Description;
    case 'achievementFamilyCocktailsLevel500Title':
      return l10n.achievementFamilyCocktailsLevel500Title;
    case 'achievementFamilyCocktailsLevel500Description':
      return l10n.achievementFamilyCocktailsLevel500Description;
    case 'achievementFamilyCocktailsLevel1000Title':
      return l10n.achievementFamilyCocktailsLevel1000Title;
    case 'achievementFamilyCocktailsLevel1000Description':
      return l10n.achievementFamilyCocktailsLevel1000Description;
    case 'achievementFamilyAppleWinesTitle':
      return l10n.achievementFamilyAppleWinesTitle;
    case 'achievementFamilyAppleWinesLevel10Title':
      return l10n.achievementFamilyAppleWinesLevel10Title;
    case 'achievementFamilyAppleWinesLevel10Description':
      return l10n.achievementFamilyAppleWinesLevel10Description;
    case 'achievementFamilyAppleWinesLevel25Title':
      return l10n.achievementFamilyAppleWinesLevel25Title;
    case 'achievementFamilyAppleWinesLevel25Description':
      return l10n.achievementFamilyAppleWinesLevel25Description;
    case 'achievementFamilyAppleWinesLevel50Title':
      return l10n.achievementFamilyAppleWinesLevel50Title;
    case 'achievementFamilyAppleWinesLevel50Description':
      return l10n.achievementFamilyAppleWinesLevel50Description;
    case 'achievementFamilyAppleWinesLevel100Title':
      return l10n.achievementFamilyAppleWinesLevel100Title;
    case 'achievementFamilyAppleWinesLevel100Description':
      return l10n.achievementFamilyAppleWinesLevel100Description;
    case 'achievementFamilyAppleWinesLevel200Title':
      return l10n.achievementFamilyAppleWinesLevel200Title;
    case 'achievementFamilyAppleWinesLevel200Description':
      return l10n.achievementFamilyAppleWinesLevel200Description;
    case 'achievementFamilyAppleWinesLevel300Title':
      return l10n.achievementFamilyAppleWinesLevel300Title;
    case 'achievementFamilyAppleWinesLevel300Description':
      return l10n.achievementFamilyAppleWinesLevel300Description;
    case 'achievementFamilyAppleWinesLevel400Title':
      return l10n.achievementFamilyAppleWinesLevel400Title;
    case 'achievementFamilyAppleWinesLevel400Description':
      return l10n.achievementFamilyAppleWinesLevel400Description;
    case 'achievementFamilyAppleWinesLevel500Title':
      return l10n.achievementFamilyAppleWinesLevel500Title;
    case 'achievementFamilyAppleWinesLevel500Description':
      return l10n.achievementFamilyAppleWinesLevel500Description;
    case 'achievementFamilyAppleWinesLevel1000Title':
      return l10n.achievementFamilyAppleWinesLevel1000Title;
    case 'achievementFamilyAppleWinesLevel1000Description':
      return l10n.achievementFamilyAppleWinesLevel1000Description;
    case 'achievementFamilyNonAlcoholicTitle':
      return l10n.achievementFamilyNonAlcoholicTitle;
    case 'achievementFamilyNonAlcoholicLevel10Title':
      return l10n.achievementFamilyNonAlcoholicLevel10Title;
    case 'achievementFamilyNonAlcoholicLevel10Description':
      return l10n.achievementFamilyNonAlcoholicLevel10Description;
    case 'achievementFamilyNonAlcoholicLevel25Title':
      return l10n.achievementFamilyNonAlcoholicLevel25Title;
    case 'achievementFamilyNonAlcoholicLevel25Description':
      return l10n.achievementFamilyNonAlcoholicLevel25Description;
    case 'achievementFamilyNonAlcoholicLevel50Title':
      return l10n.achievementFamilyNonAlcoholicLevel50Title;
    case 'achievementFamilyNonAlcoholicLevel50Description':
      return l10n.achievementFamilyNonAlcoholicLevel50Description;
    case 'achievementFamilyNonAlcoholicLevel100Title':
      return l10n.achievementFamilyNonAlcoholicLevel100Title;
    case 'achievementFamilyNonAlcoholicLevel100Description':
      return l10n.achievementFamilyNonAlcoholicLevel100Description;
    case 'achievementFamilyNonAlcoholicLevel200Title':
      return l10n.achievementFamilyNonAlcoholicLevel200Title;
    case 'achievementFamilyNonAlcoholicLevel200Description':
      return l10n.achievementFamilyNonAlcoholicLevel200Description;
    case 'achievementFamilyNonAlcoholicLevel300Title':
      return l10n.achievementFamilyNonAlcoholicLevel300Title;
    case 'achievementFamilyNonAlcoholicLevel300Description':
      return l10n.achievementFamilyNonAlcoholicLevel300Description;
    case 'achievementFamilyNonAlcoholicLevel400Title':
      return l10n.achievementFamilyNonAlcoholicLevel400Title;
    case 'achievementFamilyNonAlcoholicLevel400Description':
      return l10n.achievementFamilyNonAlcoholicLevel400Description;
    case 'achievementFamilyNonAlcoholicLevel500Title':
      return l10n.achievementFamilyNonAlcoholicLevel500Title;
    case 'achievementFamilyNonAlcoholicLevel500Description':
      return l10n.achievementFamilyNonAlcoholicLevel500Description;
    case 'achievementFamilyNonAlcoholicLevel1000Title':
      return l10n.achievementFamilyNonAlcoholicLevel1000Title;
    case 'achievementFamilyNonAlcoholicLevel1000Description':
      return l10n.achievementFamilyNonAlcoholicLevel1000Description;
    case 'achievementFamilyHomeTitle':
      return l10n.achievementFamilyHomeTitle;
    case 'achievementFamilyHomeLevel1Title':
      return l10n.achievementFamilyHomeLevel1Title;
    case 'achievementFamilyHomeLevel1Description':
      return l10n.achievementFamilyHomeLevel1Description;
    case 'achievementFamilyHomeLevel10Title':
      return l10n.achievementFamilyHomeLevel10Title;
    case 'achievementFamilyHomeLevel10Description':
      return l10n.achievementFamilyHomeLevel10Description;
    case 'achievementFamilyHomeLevel25Title':
      return l10n.achievementFamilyHomeLevel25Title;
    case 'achievementFamilyHomeLevel25Description':
      return l10n.achievementFamilyHomeLevel25Description;
    case 'achievementFamilyHomeLevel50Title':
      return l10n.achievementFamilyHomeLevel50Title;
    case 'achievementFamilyHomeLevel50Description':
      return l10n.achievementFamilyHomeLevel50Description;
    case 'achievementFamilyHomeLevel100Title':
      return l10n.achievementFamilyHomeLevel100Title;
    case 'achievementFamilyHomeLevel100Description':
      return l10n.achievementFamilyHomeLevel100Description;
    case 'achievementFamilyWorkTitle':
      return l10n.achievementFamilyWorkTitle;
    case 'achievementFamilyWorkLevel1Title':
      return l10n.achievementFamilyWorkLevel1Title;
    case 'achievementFamilyWorkLevel1Description':
      return l10n.achievementFamilyWorkLevel1Description;
    case 'achievementFamilyWorkLevel10Title':
      return l10n.achievementFamilyWorkLevel10Title;
    case 'achievementFamilyWorkLevel10Description':
      return l10n.achievementFamilyWorkLevel10Description;
    case 'achievementFamilyWorkLevel25Title':
      return l10n.achievementFamilyWorkLevel25Title;
    case 'achievementFamilyWorkLevel25Description':
      return l10n.achievementFamilyWorkLevel25Description;
    case 'achievementFamilyWorkLevel50Title':
      return l10n.achievementFamilyWorkLevel50Title;
    case 'achievementFamilyWorkLevel50Description':
      return l10n.achievementFamilyWorkLevel50Description;
    case 'achievementFamilyWorkLevel100Title':
      return l10n.achievementFamilyWorkLevel100Title;
    case 'achievementFamilyWorkLevel100Description':
      return l10n.achievementFamilyWorkLevel100Description;
    case 'achievementFamilyTravelCountriesTitle':
      return l10n.achievementFamilyTravelCountriesTitle;
    case 'achievementFamilyTravelCountriesLevel3Title':
      return l10n.achievementFamilyTravelCountriesLevel3Title;
    case 'achievementFamilyTravelCountriesLevel3Description':
      return l10n.achievementFamilyTravelCountriesLevel3Description;
    case 'achievementFamilyTravelCountriesLevel5Title':
      return l10n.achievementFamilyTravelCountriesLevel5Title;
    case 'achievementFamilyTravelCountriesLevel5Description':
      return l10n.achievementFamilyTravelCountriesLevel5Description;
    case 'achievementFamilyTravelCountriesLevel10Title':
      return l10n.achievementFamilyTravelCountriesLevel10Title;
    case 'achievementFamilyTravelCountriesLevel10Description':
      return l10n.achievementFamilyTravelCountriesLevel10Description;
    case 'achievementFamilyTravelCountriesLevel15Title':
      return l10n.achievementFamilyTravelCountriesLevel15Title;
    case 'achievementFamilyTravelCountriesLevel15Description':
      return l10n.achievementFamilyTravelCountriesLevel15Description;
    case 'achievementFamilyTravelCountriesLevel20Title':
      return l10n.achievementFamilyTravelCountriesLevel20Title;
    case 'achievementFamilyTravelCountriesLevel20Description':
      return l10n.achievementFamilyTravelCountriesLevel20Description;
    case 'achievementFamilyTravelCountriesLevel30Title':
      return l10n.achievementFamilyTravelCountriesLevel30Title;
    case 'achievementFamilyTravelCountriesLevel30Description':
      return l10n.achievementFamilyTravelCountriesLevel30Description;
    case 'achievementFamilyTravelCountriesLevel50Title':
      return l10n.achievementFamilyTravelCountriesLevel50Title;
    case 'achievementFamilyTravelCountriesLevel50Description':
      return l10n.achievementFamilyTravelCountriesLevel50Description;
    case 'achievementOccasionBirthdayTitle':
      return l10n.achievementOccasionBirthdayTitle;
    case 'achievementOccasionBirthdayDescription':
      return l10n.achievementOccasionBirthdayDescription;
    case 'achievementOccasionFirstSipAnniversaryTitle':
      return l10n.achievementOccasionFirstSipAnniversaryTitle;
    case 'achievementOccasionFirstSipAnniversaryDescription':
      return l10n.achievementOccasionFirstSipAnniversaryDescription;
    case 'achievementOccasionNewYearTitle':
      return l10n.achievementOccasionNewYearTitle;
    case 'achievementOccasionNewYearDescription':
      return l10n.achievementOccasionNewYearDescription;
    case 'achievementOccasionChristmasTitle':
      return l10n.achievementOccasionChristmasTitle;
    case 'achievementOccasionChristmasDescription':
      return l10n.achievementOccasionChristmasDescription;
    case 'achievementOccasionEasterTitle':
      return l10n.achievementOccasionEasterTitle;
    case 'achievementOccasionEasterDescription':
      return l10n.achievementOccasionEasterDescription;
    case 'achievementOccasionHalloweenTitle':
      return l10n.achievementOccasionHalloweenTitle;
    case 'achievementOccasionHalloweenDescription':
      return l10n.achievementOccasionHalloweenDescription;
    case 'achievementOccasionStPatricksDayTitle':
      return l10n.achievementOccasionStPatricksDayTitle;
    case 'achievementOccasionStPatricksDayDescription':
      return l10n.achievementOccasionStPatricksDayDescription;
    case 'achievementOccasionOktoberfestTitle':
      return l10n.achievementOccasionOktoberfestTitle;
    case 'achievementOccasionOktoberfestDescription':
      return l10n.achievementOccasionOktoberfestDescription;
    case 'achievementOccasionCarnivalTitle':
      return l10n.achievementOccasionCarnivalTitle;
    case 'achievementOccasionCarnivalDescription':
      return l10n.achievementOccasionCarnivalDescription;
    case 'achievementCountryDeTitle':
      return l10n.achievementCountryDeTitle;
    case 'achievementCountryDeLabel':
      return l10n.achievementCountryDeLabel;
    case 'achievementCountryDeDescription':
      return l10n.achievementCountryDeDescription;
    case 'achievementCountryNlTitle':
      return l10n.achievementCountryNlTitle;
    case 'achievementCountryNlLabel':
      return l10n.achievementCountryNlLabel;
    case 'achievementCountryNlDescription':
      return l10n.achievementCountryNlDescription;
    case 'achievementCountryBeTitle':
      return l10n.achievementCountryBeTitle;
    case 'achievementCountryBeLabel':
      return l10n.achievementCountryBeLabel;
    case 'achievementCountryBeDescription':
      return l10n.achievementCountryBeDescription;
    case 'achievementCountryLuTitle':
      return l10n.achievementCountryLuTitle;
    case 'achievementCountryLuLabel':
      return l10n.achievementCountryLuLabel;
    case 'achievementCountryLuDescription':
      return l10n.achievementCountryLuDescription;
    case 'achievementCountryFrTitle':
      return l10n.achievementCountryFrTitle;
    case 'achievementCountryFrLabel':
      return l10n.achievementCountryFrLabel;
    case 'achievementCountryFrDescription':
      return l10n.achievementCountryFrDescription;
    case 'achievementCountryEsTitle':
      return l10n.achievementCountryEsTitle;
    case 'achievementCountryEsLabel':
      return l10n.achievementCountryEsLabel;
    case 'achievementCountryEsDescription':
      return l10n.achievementCountryEsDescription;
    case 'achievementCountryPtTitle':
      return l10n.achievementCountryPtTitle;
    case 'achievementCountryPtLabel':
      return l10n.achievementCountryPtLabel;
    case 'achievementCountryPtDescription':
      return l10n.achievementCountryPtDescription;
    case 'achievementCountryItTitle':
      return l10n.achievementCountryItTitle;
    case 'achievementCountryItLabel':
      return l10n.achievementCountryItLabel;
    case 'achievementCountryItDescription':
      return l10n.achievementCountryItDescription;
    case 'achievementCountryAtTitle':
      return l10n.achievementCountryAtTitle;
    case 'achievementCountryAtLabel':
      return l10n.achievementCountryAtLabel;
    case 'achievementCountryAtDescription':
      return l10n.achievementCountryAtDescription;
    case 'achievementCountryChTitle':
      return l10n.achievementCountryChTitle;
    case 'achievementCountryChLabel':
      return l10n.achievementCountryChLabel;
    case 'achievementCountryChDescription':
      return l10n.achievementCountryChDescription;
    case 'achievementCountryPlTitle':
      return l10n.achievementCountryPlTitle;
    case 'achievementCountryPlLabel':
      return l10n.achievementCountryPlLabel;
    case 'achievementCountryPlDescription':
      return l10n.achievementCountryPlDescription;
    case 'achievementCountryCzTitle':
      return l10n.achievementCountryCzTitle;
    case 'achievementCountryCzLabel':
      return l10n.achievementCountryCzLabel;
    case 'achievementCountryCzDescription':
      return l10n.achievementCountryCzDescription;
    case 'achievementCountryIeTitle':
      return l10n.achievementCountryIeTitle;
    case 'achievementCountryIeLabel':
      return l10n.achievementCountryIeLabel;
    case 'achievementCountryIeDescription':
      return l10n.achievementCountryIeDescription;
    case 'achievementCountryGbTitle':
      return l10n.achievementCountryGbTitle;
    case 'achievementCountryGbLabel':
      return l10n.achievementCountryGbLabel;
    case 'achievementCountryGbDescription':
      return l10n.achievementCountryGbDescription;
    case 'achievementCountryDkTitle':
      return l10n.achievementCountryDkTitle;
    case 'achievementCountryDkLabel':
      return l10n.achievementCountryDkLabel;
    case 'achievementCountryDkDescription':
      return l10n.achievementCountryDkDescription;
    case 'achievementCountrySeTitle':
      return l10n.achievementCountrySeTitle;
    case 'achievementCountrySeLabel':
      return l10n.achievementCountrySeLabel;
    case 'achievementCountrySeDescription':
      return l10n.achievementCountrySeDescription;
    case 'achievementCountryNoTitle':
      return l10n.achievementCountryNoTitle;
    case 'achievementCountryNoLabel':
      return l10n.achievementCountryNoLabel;
    case 'achievementCountryNoDescription':
      return l10n.achievementCountryNoDescription;
    case 'achievementCountryFiTitle':
      return l10n.achievementCountryFiTitle;
    case 'achievementCountryFiLabel':
      return l10n.achievementCountryFiLabel;
    case 'achievementCountryFiDescription':
      return l10n.achievementCountryFiDescription;
    case 'achievementCountryGrTitle':
      return l10n.achievementCountryGrTitle;
    case 'achievementCountryGrLabel':
      return l10n.achievementCountryGrLabel;
    case 'achievementCountryGrDescription':
      return l10n.achievementCountryGrDescription;
    case 'achievementCountryHrTitle':
      return l10n.achievementCountryHrTitle;
    case 'achievementCountryHrLabel':
      return l10n.achievementCountryHrLabel;
    case 'achievementCountryHrDescription':
      return l10n.achievementCountryHrDescription;
    case 'achievementCountryHuTitle':
      return l10n.achievementCountryHuTitle;
    case 'achievementCountryHuLabel':
      return l10n.achievementCountryHuLabel;
    case 'achievementCountryHuDescription':
      return l10n.achievementCountryHuDescription;
    case 'achievementCountryRoTitle':
      return l10n.achievementCountryRoTitle;
    case 'achievementCountryRoLabel':
      return l10n.achievementCountryRoLabel;
    case 'achievementCountryRoDescription':
      return l10n.achievementCountryRoDescription;
    case 'achievementCountryTrTitle':
      return l10n.achievementCountryTrTitle;
    case 'achievementCountryTrLabel':
      return l10n.achievementCountryTrLabel;
    case 'achievementCountryTrDescription':
      return l10n.achievementCountryTrDescription;
    case 'achievementCountryUsTitle':
      return l10n.achievementCountryUsTitle;
    case 'achievementCountryUsLabel':
      return l10n.achievementCountryUsLabel;
    case 'achievementCountryUsDescription':
      return l10n.achievementCountryUsDescription;
    case 'achievementCountryJpTitle':
      return l10n.achievementCountryJpTitle;
    case 'achievementCountryJpLabel':
      return l10n.achievementCountryJpLabel;
    case 'achievementCountryJpDescription':
      return l10n.achievementCountryJpDescription;
    case 'achievementCountrySiTitle':
      return l10n.achievementCountrySiTitle;
    case 'achievementCountrySiLabel':
      return l10n.achievementCountrySiLabel;
    case 'achievementCountrySiDescription':
      return l10n.achievementCountrySiDescription;
    case 'achievementCountryMcTitle':
      return l10n.achievementCountryMcTitle;
    case 'achievementCountryMcLabel':
      return l10n.achievementCountryMcLabel;
    case 'achievementCountryMcDescription':
      return l10n.achievementCountryMcDescription;
    case 'achievementsTab':
      return l10n.achievementsTab;
    case 'achievementsTitle':
      return l10n.achievementsTitle;
    case 'achievementsBadgesEarned':
      return l10n.achievementsBadgesEarned;
    case 'achievementsFilterAll':
      return l10n.achievementsFilterAll;
    case 'achievementsFilterUnlocked':
      return l10n.achievementsFilterUnlocked;
    case 'achievementsFilterLocked':
      return l10n.achievementsFilterLocked;
    case 'achievementsRecentlyUnlocked':
      return l10n.achievementsRecentlyUnlocked;
    case 'achievementsViewAll':
      return l10n.achievementsViewAll;
    case 'achievementsSetupRequired':
      return l10n.achievementsSetupRequired;
    case 'achievementsSetUpNow':
      return l10n.achievementsSetUpNow;
    case 'achievementsEarnableToday':
      return l10n.achievementsEarnableToday;
    case 'achievementsNextEligible':
      return l10n.achievementsNextEligible;
    case 'achievementsUnlocked':
      return l10n.achievementsUnlocked;
    case 'achievementsLocked':
      return l10n.achievementsLocked;
    case 'achievementsCompleted':
      return l10n.achievementsCompleted;
    case 'achievementsSummaryBackfillTitle':
      return l10n.achievementsSummaryBackfillTitle;
    case 'achievementReminders':
      return l10n.achievementReminders;
    case 'achievementRemindersBody':
      return l10n.achievementRemindersBody;
    case 'achievementsCategoryTotals':
      return l10n.achievementsCategoryTotals;
    case 'achievementsCategoryStreaks':
      return l10n.achievementsCategoryStreaks;
    case 'achievementsCategoryDrinkTypes':
      return l10n.achievementsCategoryDrinkTypes;
    case 'achievementsCategoryOccasions':
      return l10n.achievementsCategoryOccasions;
    case 'achievementsCategoryPlaces':
      return l10n.achievementsCategoryPlaces;
    case 'achievementsCategoryTravel':
      return l10n.achievementsCategoryTravel;
    case 'achievementsCategoryCountries':
      return l10n.achievementsCategoryCountries;
    case 'achievementReminderBirthdayTitle':
      return l10n.achievementReminderBirthdayTitle;
    case 'achievementReminderBirthdayBody':
      return l10n.achievementReminderBirthdayBody;
    case 'achievementReminderNewYearTitle':
      return l10n.achievementReminderNewYearTitle;
    case 'achievementReminderNewYearBody':
      return l10n.achievementReminderNewYearBody;
    case 'achievementReminderChristmasTitle':
      return l10n.achievementReminderChristmasTitle;
    case 'achievementReminderChristmasBody':
      return l10n.achievementReminderChristmasBody;
    case 'achievementReminderEasterTitle':
      return l10n.achievementReminderEasterTitle;
    case 'achievementReminderEasterBody':
      return l10n.achievementReminderEasterBody;
    case 'achievementReminderHalloweenTitle':
      return l10n.achievementReminderHalloweenTitle;
    case 'achievementReminderHalloweenBody':
      return l10n.achievementReminderHalloweenBody;
    case 'achievementReminderStPatricksDayTitle':
      return l10n.achievementReminderStPatricksDayTitle;
    case 'achievementReminderStPatricksDayBody':
      return l10n.achievementReminderStPatricksDayBody;
    case 'achievementReminderOktoberfestTitle':
      return l10n.achievementReminderOktoberfestTitle;
    case 'achievementReminderOktoberfestBody':
      return l10n.achievementReminderOktoberfestBody;
    case 'achievementReminderCarnivalTitle':
      return l10n.achievementReminderCarnivalTitle;
    case 'achievementReminderCarnivalBody':
      return l10n.achievementReminderCarnivalBody;
    case 'achievementReminderGenericTitle':
      return l10n.achievementReminderGenericTitle;
    case 'achievementReminderGenericBody':
      return l10n.achievementReminderGenericBody;
    case 'achievementReminderFirstSipAnniversaryBody':
      return l10n.achievementReminderFirstSipAnniversaryBody;
    default:
      return key;
  }
}
