import 'dart:collection';
import 'dart:convert';
import 'dart:io';

const _sourceDirectory = 'lib/l10n';
const _outputPath = 'supabase/functions/_shared/notification_l10n.ts';
const _defaultCatalogSourcePath = 'lib/src/models.dart';

const _notificationTemplateKeys = <String, Map<String, String>>{
  'friend_request_sent': <String, String>{
    'title': 'notificationFriendRequestSentTitle',
    'body': 'notificationFriendRequestSentBody',
  },
  'friend_request_accepted': <String, String>{
    'title': 'notificationFriendRequestAcceptedTitle',
    'body': 'notificationFriendRequestAcceptedBody',
  },
  'friend_request_rejected': <String, String>{
    'title': 'notificationFriendRequestRejectedTitle',
    'body': 'notificationFriendRequestRejectedBody',
  },
  'friend_removed': <String, String>{
    'title': 'notificationFriendRemovedTitle',
    'body': 'notificationFriendRemovedBody',
  },
  'friend_drink_logged': <String, String>{
    'title': 'notificationFriendDrinkLoggedTitle',
    'body': 'notificationFriendDrinkLoggedBody',
  },
};

void main() {
  final messages = SplayTreeMap<String, Map<String, Map<String, String>>>();
  final arbFiles =
      Directory(_sourceDirectory)
          .listSync()
          .whereType<File>()
          .where((file) => RegExp(r'app_[a-zA-Z_-]+\.arb$').hasMatch(file.path))
          .toList()
        ..sort((left, right) => left.path.compareTo(right.path));

  for (final arbFile in arbFiles) {
    final locale = _localeFromPath(arbFile.path);
    final arb = jsonDecode(arbFile.readAsStringSync()) as Map<String, dynamic>;
    final localeMessages = <String, Map<String, String>>{};

    for (final entry in _notificationTemplateKeys.entries) {
      final keys = entry.value;
      localeMessages[entry.key] = <String, String>{
        'title': _requiredString(arb, keys['title']!, arbFile.path),
        'body': _requiredString(arb, keys['body']!, arbFile.path),
      };
    }

    messages[locale] = localeMessages;
  }

  if (!messages.containsKey('en')) {
    throw StateError('Expected $_sourceDirectory/app_en.arb to exist.');
  }

  File(
    _outputPath,
  ).writeAsStringSync(_typescriptFor(messages, _defaultDrinkNames()));
  _formatOutput();
}

String _localeFromPath(String path) {
  final match = RegExp(r'app_([a-zA-Z_-]+)\.arb$').firstMatch(path);
  if (match == null) {
    throw ArgumentError.value(
      path,
      'path',
      'Expected an app_<locale>.arb file.',
    );
  }
  return match.group(1)!.replaceAll('_', '-');
}

String _requiredString(Map<String, dynamic> arb, String key, String path) {
  final value = arb[key];
  if (value is String && value.trim().isNotEmpty) {
    return value;
  }
  throw StateError('Missing non-empty "$key" in $path.');
}

Map<String, Map<String, String>> _defaultDrinkNames() {
  final english = SplayTreeMap<String, String>();
  final german = SplayTreeMap<String, String>();
  final source = File(_defaultCatalogSourcePath).readAsStringSync();
  final matches = RegExp(
    r"\(\s*'([^']+)'\s*,\s*DrinkCategory\.[a-zA-Z]+\s*,\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*(?:null|[0-9.]+)\s*,?\s*\)",
    dotAll: true,
  ).allMatches(source);
  if (matches.isEmpty) {
    throw StateError(
      'Expected default drink tuples in $_defaultCatalogSourcePath.',
    );
  }
  for (final match in matches) {
    english[match.group(1)!] = match.group(2)!;
    german[match.group(1)!] = match.group(3)!;
  }
  return <String, Map<String, String>>{'en': english, 'de': german};
}

String _typescriptFor(
  Map<String, Map<String, Map<String, String>>> messages,
  Map<String, Map<String, String>> defaultDrinkNames,
) {
  const encoder = JsonEncoder.withIndent('  ');
  final encodedMessages = encoder.convert(messages);
  final encodedDefaultDrinkNames = encoder.convert(defaultDrinkNames);
  return '''
// Generated by tool/generate_notification_push_l10n.dart from lib/l10n/app_*.arb.
// Regenerate from the repository root with:
// dart run tool/generate_notification_push_l10n.dart

export type NotificationPushInput = {
  type: string;
  locale: string;
  templateArgs: Record<string, unknown> | null;
  senderDisplayName: string;
};

type NotificationMessage = {
  title: string;
  body?: string;
};

const fallbackLocale = "en";
const fallbackTitle = "Glass Trail";

const messages: Record<string, Record<string, NotificationMessage>> = $encodedMessages;
const defaultDrinkNames: Record<string, Record<string, string>> = $encodedDefaultDrinkNames;

export function notificationPushTitle(input: NotificationPushInput): string {
  const title = messageFor(input.type, input.locale)?.title ?? fallbackTitle;
  return formatTemplate(title, input);
}

export function notificationPushBody(
  input: NotificationPushInput,
): string | null {
  const body = messageFor(input.type, input.locale)?.body;
  return body == null ? null : compactBody(formatTemplate(body, input));
}

function messageFor(type: string, locale: string): NotificationMessage | null {
  const normalizedLocale = normalizeLocale(locale);
  return messages[normalizedLocale]?.[type] ??
    messages[languageFromLocale(normalizedLocale)]?.[type] ??
    messages[fallbackLocale]?.[type] ??
    null;
}

function formatTemplate(template: string, input: NotificationPushInput): string {
  return template
    .replaceAll("{name}", senderDisplayName(input))
    .replaceAll("{drink}", localizedDrinkName(input))
    .replaceAll("{commentLine}", prefixedNotificationLine("🗨️", templateString(input, "comment")))
    .replaceAll(
      "{locationAddressLine}",
      prefixedNotificationLine(
        "📍",
        templateString(input, "locationAddress", "location_address"),
      ),
    )
    .replaceAll("{comment}", templateString(input, "comment"))
    .replaceAll("{locationAddress}", templateString(input, "locationAddress", "location_address"));
}

function senderDisplayName(input: NotificationPushInput): string {
  const fromTemplateArgs = templateString(input, "senderDisplayName", "sender_display_name");
  if (fromTemplateArgs.length > 0) {
    return fromTemplateArgs;
  }

  const fromRow = stringValue(input.senderDisplayName);
  return fromRow.length > 0 ? fromRow : "Glass Trail User";
}

function localizedDrinkName(input: NotificationPushInput): string {
  const drinkId = templateString(input, "drinkId", "drink_id");
  const locale = languageFromLocale(normalizeLocale(input.locale));
  const localized = stringValue(defaultDrinkNames[locale]?.[drinkId]) ||
    stringValue(defaultDrinkNames[fallbackLocale]?.[drinkId]);
  if (localized.length > 0) {
    return localized;
  }
  return templateString(input, "drinkName", "drink_name") || "a drink";
}

function templateString(
  input: NotificationPushInput,
  primary: string,
  fallback?: string,
): string {
  return stringValue(input.templateArgs?.[primary]) ||
    (fallback == null ? "" : stringValue(input.templateArgs?.[fallback]));
}

function prefixedNotificationLine(prefix: string, value: string): string {
  return value.length > 0 ? `\${prefix} \${value}` : "";
}

function compactBody(value: string): string | null {
  const body = value
    .split("\\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join("\\n");
  return body.length > 0 ? body : null;
}

function normalizeLocale(value: string): string {
  const locale = stringValue(value).replaceAll("_", "-");
  return locale.length > 0 ? locale : fallbackLocale;
}

function languageFromLocale(locale: string): string {
  return locale.split("-")[0] || fallbackLocale;
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}
''';
}

void _formatOutput() {
  try {
    final result = Process.runSync('deno', <String>['fmt', _outputPath]);
    if (result.exitCode != 0) {
      stderr.writeln('Skipped deno fmt: ${result.stderr}');
    }
  } on ProcessException catch (error) {
    stderr.writeln('Skipped deno fmt: ${error.message}');
  }
}
