insert into public.drink_categories (slug, sort_order, name_en, name_de)
values
  ('beer', 1, 'Beer', 'Bier'),
  ('wine', 2, 'Wine', 'Wein'),
  ('sparklingWines', 3, 'Sparkling Wines', 'Schaumweine'),
  ('longdrinks', 4, 'Longdrinks', 'Langdrinks'),
  ('spirits', 5, 'Spirits', 'Spirituosen'),
  ('shots', 6, 'Shots', 'Shots'),
  ('cocktails', 7, 'Cocktails', 'Cocktails'),
  ('appleWines', 8, 'Apple Wines', 'Apfelweine'),
  ('nonAlcoholic', 9, 'Non-alcoholic', 'Alkoholfrei')
on conflict (slug) do update
set
  sort_order = excluded.sort_order,
  name_en = excluded.name_en,
  name_de = excluded.name_de;

insert into public.global_drinks (
  id,
  category_slug,
  name_en,
  name_de,
  default_volume_ml
)
values
  ('beer-pils', 'beer', 'Pils', 'Pils', 330),
  ('beer-helles', 'beer', 'Helles', 'Helles', 500),
  ('beer-weizen', 'beer', 'Weizen', 'Weizen', 500),
  ('beer-kellerbier', 'beer', 'Kellerbier', 'Kellerbier', 500),
  ('beer-kölsch', 'beer', 'Kölsch', 'Kölsch', 200),
  ('beer-alt', 'beer', 'Alt', 'Alt', 250),
  ('beer-ipa', 'beer', 'IPA', 'IPA', 330),
  ('beer-goassmass', 'beer', 'Goaßmaß', 'Goaßmaß', 1000),
  ('beer-mass', 'beer', 'Maß', 'Maß', 1000),
  ('beer-stout', 'beer', 'Stout', 'Stout', 330),
  ('beer-radler', 'beer', 'Radler', 'Radler', 500),
  ('wine-red-wine', 'wine', 'Red Wine', 'Rotwein', 150),
  ('wine-white-wine', 'wine', 'White Wine', 'Weißwein', 150),
  ('wine-rosé-wine', 'wine', 'Rosé Wine', 'Roséwein', 150),
  ('wine-aperol-spritz', 'wine', 'Aperol Spritz', 'Aperol Spritz', 200),
  ('wine-mulled-wine', 'wine', 'Mulled Wine', 'Glühwein', 200),
  ('wine-wine-spritzer', 'wine', 'Wine Spritzer', 'Weinschorle', 250),
  ('wine-spritzer', 'wine', 'Spritzer', 'Spritzer', 250),
  ('wine-sangria', 'wine', 'Sangria', 'Sangria', 250),
  ('wine-sparkling-wine', 'sparklingWines', 'Sparkling Wine', 'Sekt', 120),
  ('sparklingWines-champagne', 'sparklingWines', 'Champagne', 'Champagner', 120),
  ('longdrinks-cuba-libre', 'longdrinks', 'Cuba Libre', 'Cuba Libre', 250),
  ('longdrinks-gin-tonic', 'longdrinks', 'Gin & Tonic', 'Gin & Tonic', 250),
  ('longdrinks-jacki-cola', 'longdrinks', 'Jacki Cola', 'Jacki Cola', 250),
  ('longdrinks-vodka-o', 'longdrinks', 'Vodka O', 'Vodka O', 250),
  ('longdrinks-vodka-bull', 'longdrinks', 'Vodka Bull', 'Vodka Bull', 250),
  ('longdrinks-longdrink', 'longdrinks', 'Longdrink', 'Longdrink', null),
  ('spirits-vodka', 'spirits', 'Vodka', 'Wodka', 40),
  ('spirits-gin', 'spirits', 'Gin', 'Gin', 40),
  ('spirits-rum', 'spirits', 'Rum', 'Rum', 40),
  ('spirits-whiskey', 'spirits', 'Whiskey', 'Whiskey', 40),
  ('spirits-cognac', 'spirits', 'Cognac', 'Cognac', 40),
  ('shots-jaegermeister', 'shots', 'Jägermeister', 'Jägermeister', 20),
  ('shots-berliner-luft', 'shots', 'Berliner Luft', 'Berliner Luft', 20),
  ('shots-pfeffi', 'shots', 'Pfeffi', 'Pfeffi', 20),
  ('shots-ficken', 'shots', 'Ficken', 'Ficken', 20),
  ('spirits-tequila', 'shots', 'Tequila', 'Tequila', 40),
  ('shots-limoncello', 'shots', 'Limoncello', 'Limoncello', 20),
  ('cocktails-mojito', 'cocktails', 'Mojito', 'Mojito', 250),
  ('cocktails-margarita', 'cocktails', 'Margarita', 'Margarita', 180),
  ('cocktails-martini', 'cocktails', 'Martini', 'Martini', 160),
  ('cocktails-cocktail', 'cocktails', 'Cocktail', 'Cocktail', 250),
  ('cocktails-caipirinha', 'cocktails', 'Caipirinha', 'Caipirinha', 250),
  ('appleWines-hard-seltzer', 'appleWines', 'Hard Seltzer', 'Hard Seltzer', 330),
  ('appleWines-apple-wine', 'appleWines', 'Apple Wine', 'Apfelwein', 500),
  ('appleWines-cider', 'appleWines', 'Cider', 'Cider', 330),
  ('nonAlcoholic-water', 'nonAlcoholic', 'Water', 'Wasser', 250),
  ('nonAlcoholic-juice', 'nonAlcoholic', 'Juice', 'Saft', 250),
  ('nonAlcoholic-sparkling-water', 'nonAlcoholic', 'Sparkling Water', 'Sprudelwasser', 250),
  ('nonAlcoholic-tea', 'nonAlcoholic', 'Tea', 'Tee', 300),
  ('nonAlcoholic-coffee', 'nonAlcoholic', 'Coffee', 'Kaffee', 200),
  ('nonAlcoholic-energy-drink', 'nonAlcoholic', 'Energy Drink', 'Energy Drink', 250),
  ('nonAlcoholic-cola', 'nonAlcoholic', 'Cola', 'Cola', 330),
  ('nonAlcoholic-lemonade', 'nonAlcoholic', 'Lemonade', 'Limonade', 330)
on conflict (id) do update
set
  category_slug = excluded.category_slug,
  name_en = excluded.name_en,
  name_de = excluded.name_de,
  default_volume_ml = excluded.default_volume_ml;
